"""fase2_approvals

Revision ID: 2cc69e555951
Revises: 3f90b7247b4b
Create Date: 2026-05-21 16:21:27.752576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2cc69e555951'
down_revision: Union[str, None] = '3f90b7247b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_comments_approval_id'), 'approval_comments', ['approval_id'], unique=False)
    op.create_index(op.f('ix_approval_comments_created_at'), 'approval_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_approval_comments_id'), 'approval_comments', ['id'], unique=False)
    op.create_index(op.f('ix_approval_comments_user_id'), 'approval_comments', ['user_id'], unique=False)
    op.create_table('approval_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.Column('decided_by_user_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_decisions_approval_id'), 'approval_decisions', ['approval_id'], unique=False)
    op.create_index(op.f('ix_approval_decisions_created_at'), 'approval_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_approval_decisions_decided_by_user_id'), 'approval_decisions', ['decided_by_user_id'], unique=False)
    op.create_index(op.f('ix_approval_decisions_id'), 'approval_decisions', ['id'], unique=False)
    op.add_column('approvals', sa.Column('module_slug', sa.String(), nullable=False))
    op.add_column('approvals', sa.Column('requester_user_id', sa.Integer(), nullable=False))
    op.add_column('approvals', sa.Column('approver_user_id', sa.Integer(), nullable=True))
    op.add_column('approvals', sa.Column('risk_level', sa.String(), nullable=False))
    op.add_column('approvals', sa.Column('action_type', sa.String(), nullable=False))
    op.add_column('approvals', sa.Column('action_payload', sa.JSON(), nullable=False))
    op.add_column('approvals', sa.Column('result_payload', sa.JSON(), nullable=True))
    op.add_column('approvals', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('approvals', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_approvals_approver_user_id'), 'approvals', ['approver_user_id'], unique=False)
    op.create_index(op.f('ix_approvals_created_at'), 'approvals', ['created_at'], unique=False)
    op.create_index(op.f('ix_approvals_module_slug'), 'approvals', ['module_slug'], unique=False)
    op.create_index(op.f('ix_approvals_requester_user_id'), 'approvals', ['requester_user_id'], unique=False)
    op.create_index(op.f('ix_approvals_risk_level'), 'approvals', ['risk_level'], unique=False)
    op.create_index(op.f('ix_approvals_status'), 'approvals', ['status'], unique=False)
    op.drop_constraint(op.f('approvals_decider_id_fkey'), 'approvals', type_='foreignkey')
    op.drop_constraint(op.f('approvals_requester_id_fkey'), 'approvals', type_='foreignkey')
    op.create_foreign_key(None, 'approvals', 'users', ['requester_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'approvals', 'users', ['approver_user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('approvals', 'decider_id')
    op.drop_column('approvals', 'requester_id')
    op.drop_column('approvals', 'module')
    op.drop_column('approvals', 'data_json')
    op.drop_column('approvals', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvals', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('approvals', sa.Column('data_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('approvals', sa.Column('module', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('approvals', sa.Column('requester_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('approvals', sa.Column('decider_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'approvals', type_='foreignkey')
    op.drop_constraint(None, 'approvals', type_='foreignkey')
    op.create_foreign_key(op.f('approvals_requester_id_fkey'), 'approvals', 'users', ['requester_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('approvals_decider_id_fkey'), 'approvals', 'users', ['decider_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_approvals_status'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_risk_level'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_requester_user_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_module_slug'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_created_at'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_approver_user_id'), table_name='approvals')
    op.drop_column('approvals', 'updated_at')
    op.drop_column('approvals', 'expires_at')
    op.drop_column('approvals', 'result_payload')
    op.drop_column('approvals', 'action_payload')
    op.drop_column('approvals', 'action_type')
    op.drop_column('approvals', 'risk_level')
    op.drop_column('approvals', 'approver_user_id')
    op.drop_column('approvals', 'requester_user_id')
    op.drop_column('approvals', 'module_slug')
    op.drop_index(op.f('ix_approval_decisions_id'), table_name='approval_decisions')
    op.drop_index(op.f('ix_approval_decisions_decided_by_user_id'), table_name='approval_decisions')
    op.drop_index(op.f('ix_approval_decisions_created_at'), table_name='approval_decisions')
    op.drop_index(op.f('ix_approval_decisions_approval_id'), table_name='approval_decisions')
    op.drop_table('approval_decisions')
    op.drop_index(op.f('ix_approval_comments_user_id'), table_name='approval_comments')
    op.drop_index(op.f('ix_approval_comments_id'), table_name='approval_comments')
    op.drop_index(op.f('ix_approval_comments_created_at'), table_name='approval_comments')
    op.drop_index(op.f('ix_approval_comments_approval_id'), table_name='approval_comments')
    op.drop_table('approval_comments')
    # ### end Alembic commands ###
