"""add automation callback logs

Revision ID: 5cde65cfbabd
Revises: 873b65913138
Create Date: 2026-06-02 14:17:53.274866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cde65cfbabd'
down_revision: Union[str, None] = '873b65913138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_callback_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=True),
    sa.Column('workflow_name', sa.String(), nullable=True),
    sa.Column('execution_id', sa.String(), nullable=True),
    sa.Column('callback_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('action_intent_id', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_logs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_callback_logs_callback_type'), 'automation_callback_logs', ['callback_type'], unique=False)
    op.create_index(op.f('ix_automation_callback_logs_event_id'), 'automation_callback_logs', ['event_id'], unique=False)
    op.create_index(op.f('ix_automation_callback_logs_event_type'), 'automation_callback_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_automation_callback_logs_idempotency_key'), 'automation_callback_logs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_automation_callback_logs_received_at'), 'automation_callback_logs', ['received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_automation_callback_logs_received_at'), table_name='automation_callback_logs')
    op.drop_index(op.f('ix_automation_callback_logs_idempotency_key'), table_name='automation_callback_logs')
    op.drop_index(op.f('ix_automation_callback_logs_event_type'), table_name='automation_callback_logs')
    op.drop_index(op.f('ix_automation_callback_logs_event_id'), table_name='automation_callback_logs')
    op.drop_index(op.f('ix_automation_callback_logs_callback_type'), table_name='automation_callback_logs')
    op.drop_table('automation_callback_logs')
    # ### end Alembic commands ###
