"""fix it integer primary key identity

Revision ID: 6e2b5c9d1a4f
Revises: c9f2b6a1d4e7
Create Date: 2026-06-23
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "6e2b5c9d1a4f"
down_revision: Union[str, None] = "c9f2b6a1d4e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


IT_INTEGER_PK_TABLES = (
    "it_sla_policies",
    "it_tickets",
    "it_ticket_comments",
    "it_ticket_checklists",
    "it_ticket_checklist_items",
    "it_checklist_templates",
    "it_ticket_time_logs",
    "it_ticket_attachments",
    "it_assets",
    "it_access_catalog",
    "it_access_requests",
    "it_credentials_vault",
    "it_certificates",
    "it_network_items",
    "it_maintenance_records",
    "it_ticket_kanban_links",
    "it_activity",
)


def _quote_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _identity_upgrade_sql(table_name: str) -> str:
    table_literal = _quote_literal(table_name)
    qualified_literal = _quote_literal(f"public.{table_name}")
    return f"""
    DO $$
    DECLARE
        seq_name text;
        max_id bigint;
    BEGIN
        IF to_regclass({qualified_literal}) IS NOT NULL THEN
            IF EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_schema = 'public'
                  AND table_name = {table_literal}
                  AND column_name = 'id'
                  AND identity_generation IS NULL
                  AND column_default IS NULL
            ) THEN
                EXECUTE format(
                    'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY',
                    {table_literal}
                );
            END IF;

            seq_name := pg_get_serial_sequence(format('public.%I', {table_literal}), 'id');
            IF seq_name IS NOT NULL THEN
                EXECUTE format('SELECT COALESCE(MAX(id), 0) FROM %I', {table_literal}) INTO max_id;
                EXECUTE format('SELECT setval(%L, %s, false)', seq_name, max_id + 1);
            END IF;
        END IF;
    END $$;
    """


def _identity_downgrade_sql(table_name: str) -> str:
    table_literal = _quote_literal(table_name)
    qualified_literal = _quote_literal(f"public.{table_name}")
    return f"""
    DO $$
    BEGIN
        IF to_regclass({qualified_literal}) IS NOT NULL THEN
            IF EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_schema = 'public'
                  AND table_name = {table_literal}
                  AND column_name = 'id'
                  AND identity_generation IS NOT NULL
            ) THEN
                EXECUTE format(
                    'ALTER TABLE %I ALTER COLUMN id DROP IDENTITY IF EXISTS',
                    {table_literal}
                );
            END IF;
        END IF;
    END $$;
    """


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    for table_name in IT_INTEGER_PK_TABLES:
        op.execute(sa.text(_identity_upgrade_sql(table_name)))


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    for table_name in reversed(IT_INTEGER_PK_TABLES):
        op.execute(sa.text(_identity_downgrade_sql(table_name)))
