"""create legacy import tables

Revision ID: e3d1f205e393
Revises: b52d9f32b91b
Create Date: 2026-06-05 08:27:25.196919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3d1f205e393'
down_revision: Union[str, None] = 'b52d9f32b91b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legacy_import_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_app', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_path_masked', sa.String(), nullable=False),
    sa.Column('module_target', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legacy_import_batches_created_at'), 'legacy_import_batches', ['created_at'], unique=False)
    op.create_index(op.f('ix_legacy_import_batches_created_by_user_id'), 'legacy_import_batches', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_legacy_import_batches_module_target'), 'legacy_import_batches', ['module_target'], unique=False)
    op.create_index(op.f('ix_legacy_import_batches_source_app'), 'legacy_import_batches', ['source_app'], unique=False)
    op.create_index(op.f('ix_legacy_import_batches_status'), 'legacy_import_batches', ['status'], unique=False)

    op.create_table('legacy_import_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('source_app', sa.String(), nullable=False),
    sa.Column('source_table_or_sheet', sa.String(), nullable=True),
    sa.Column('source_row_id', sa.String(), nullable=True),
    sa.Column('module_target', sa.String(), nullable=False),
    sa.Column('entity_target', sa.String(), nullable=False),
    sa.Column('raw_data_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('normalized_data_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('detected_duplicates_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('issues_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['legacy_import_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legacy_import_rows_batch_id'), 'legacy_import_rows', ['batch_id'], unique=False)
    op.create_index(op.f('ix_legacy_import_rows_created_at'), 'legacy_import_rows', ['created_at'], unique=False)
    op.create_index(op.f('ix_legacy_import_rows_entity_target'), 'legacy_import_rows', ['entity_target'], unique=False)
    op.create_index(op.f('ix_legacy_import_rows_module_target'), 'legacy_import_rows', ['module_target'], unique=False)
    op.create_index(op.f('ix_legacy_import_rows_reviewed_by_user_id'), 'legacy_import_rows', ['reviewed_by_user_id'], unique=False)
    op.create_index(op.f('ix_legacy_import_rows_source_app'), 'legacy_import_rows', ['source_app'], unique=False)
    op.create_index(op.f('ix_legacy_import_rows_source_row_id'), 'legacy_import_rows', ['source_row_id'], unique=False)
    op.create_index(op.f('ix_legacy_import_rows_status'), 'legacy_import_rows', ['status'], unique=False)

    op.create_table('legacy_duplicate_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('row_id', sa.UUID(), nullable=False),
    sa.Column('target_entity_type', sa.String(), nullable=False),
    sa.Column('target_entity_id', sa.String(), nullable=True),
    sa.Column('match_type', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['row_id'], ['legacy_import_rows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legacy_duplicate_candidates_created_at'), 'legacy_duplicate_candidates', ['created_at'], unique=False)
    op.create_index(op.f('ix_legacy_duplicate_candidates_row_id'), 'legacy_duplicate_candidates', ['row_id'], unique=False)
    op.create_index(op.f('ix_legacy_duplicate_candidates_status'), 'legacy_duplicate_candidates', ['status'], unique=False)
    op.create_index(op.f('ix_legacy_duplicate_candidates_target_entity_id'), 'legacy_duplicate_candidates', ['target_entity_id'], unique=False)

    op.create_table('legacy_import_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('row_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_by_user_id', sa.Integer(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['row_id'], ['legacy_import_rows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legacy_import_decisions_decided_at'), 'legacy_import_decisions', ['decided_at'], unique=False)
    op.create_index(op.f('ix_legacy_import_decisions_decided_by_user_id'), 'legacy_import_decisions', ['decided_by_user_id'], unique=False)
    op.create_index(op.f('ix_legacy_import_decisions_row_id'), 'legacy_import_decisions', ['row_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('legacy_import_decisions')
    op.drop_table('legacy_duplicate_candidates')
    op.drop_table('legacy_import_rows')
    op.drop_table('legacy_import_batches')
    # ### end Alembic commands ###
